#!/usr/bin/env bash

set -eu

currentDir=$(dirname "${BASH_SOURCE[0]}")
source $currentDir/common

touch pids

for proj in "${projects[@]}"; do
    yarn "project:serve:$proj" > /dev/null 2>&1 &
    pid=$!
    echo $pid >> pids
done
